/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import controlador.LibroController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author munoz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnPrincipal = new javax.swing.JTabbedPane();
        panLibros = new javax.swing.JPanel();
        panIngresoLibro = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtEjemplaresDisponibles = new javax.swing.JTextField();
        txtFechaPublicacion = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblEditorial = new javax.swing.JLabel();
        lblEjemplaresDisponibles = new javax.swing.JLabel();
        lblFechaPublicacion = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        btnRegistrarLibro = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        panUsuarios = new javax.swing.JPanel();
        panPrestamos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panIngresoLibro.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso"));
        panIngresoLibro.setToolTipText("Ingreso");
        panIngresoLibro.setName(""); // NOI18N

        lblTitulo.setText("Titulo");

        lblEditorial.setText("Editorial");

        lblEjemplaresDisponibles.setText("Disponibles");

        lblFechaPublicacion.setText("Publicacion");

        lblGenero.setText("Genero");

        btnRegistrarLibro.setBackground(new java.awt.Color(153, 255, 102));
        btnRegistrarLibro.setText("Registrar");
        btnRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panIngresoLibroLayout = new javax.swing.GroupLayout(panIngresoLibro);
        panIngresoLibro.setLayout(panIngresoLibroLayout);
        panIngresoLibroLayout.setHorizontalGroup(
            panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIngresoLibroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panIngresoLibroLayout.createSequentialGroup()
                        .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo))
                        .addGap(18, 18, 18)
                        .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditorial))
                        .addGap(18, 18, 18)
                        .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEjemplaresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEjemplaresDisponibles))
                        .addGap(18, 18, 18)
                        .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaPublicacion))
                        .addGap(18, 18, 18)
                        .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenero)
                            .addGroup(panIngresoLibroLayout.createSequentialGroup()
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrarLibro)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panIngresoLibroLayout.setVerticalGroup(
            panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIngresoLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblEditorial)
                    .addComponent(lblEjemplaresDisponibles)
                    .addComponent(lblFechaPublicacion)
                    .addComponent(lblGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panIngresoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEjemplaresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensaje))
        );

        javax.swing.GroupLayout panLibrosLayout = new javax.swing.GroupLayout(panLibros);
        panLibros.setLayout(panLibrosLayout);
        panLibrosLayout.setHorizontalGroup(
            panLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panIngresoLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLibrosLayout.setVerticalGroup(
            panLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLibrosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panIngresoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        panIngresoLibro.getAccessibleContext().setAccessibleName("Ingreso");

        tpnPrincipal.addTab("Libros", panLibros);

        javax.swing.GroupLayout panUsuariosLayout = new javax.swing.GroupLayout(panUsuarios);
        panUsuarios.setLayout(panUsuariosLayout);
        panUsuariosLayout.setHorizontalGroup(
            panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        panUsuariosLayout.setVerticalGroup(
            panUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        tpnPrincipal.addTab("Usuarios", panUsuarios);

        javax.swing.GroupLayout panPrestamosLayout = new javax.swing.GroupLayout(panPrestamos);
        panPrestamos.setLayout(panPrestamosLayout);
        panPrestamosLayout.setHorizontalGroup(
            panPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        panPrestamosLayout.setVerticalGroup(
            panPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        tpnPrincipal.addTab("Prestamos", panPrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLibroActionPerformed
        // TODO add your handling code here:
        /*SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        
        String titulo = txtTitulo.getText();
        String editorial = txtEditorial.getText();
        int ejemplaresDisponibles = Integer.parseInt(txtEjemplaresDisponibles.getText());
        Date fechaPublicacion = new Date();
        try {
            fechaPublicacion = formatoFecha.parse(txtFechaPublicacion.getText());
        } catch (ParseException ex) {
            System.err.println("Error de fecha");
        }
        String genero = txtGenero.getText();
        
        LibroController controlador = new LibroController();
        boolean respuesta = controlador.agregarLibro(titulo, editorial, ejemplaresDisponibles, fechaPublicacion, genero);
        
        Timer timer = new Timer(3000, event ->{
            lblMensaje.setText("");
        });
        timer.setRepeats(false);
        
        if(respuesta){
            lblMensaje.setText("Registrado");
        }
        else{
            lblMensaje.setText("No pudo ser registrado");
        }
        timer.start();*/
    }//GEN-LAST:event_btnRegistrarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarLibro;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblEjemplaresDisponibles;
    private javax.swing.JLabel lblFechaPublicacion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panIngresoLibro;
    private javax.swing.JPanel panLibros;
    private javax.swing.JPanel panPrestamos;
    private javax.swing.JPanel panUsuarios;
    private javax.swing.JTabbedPane tpnPrincipal;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtEjemplaresDisponibles;
    private javax.swing.JTextField txtFechaPublicacion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
